libraryapp/urls.py
from django.conf.urls import url
from .views import *
from django.conf.urls import url, include
from django.urls import path


# This file will define all of the URLs that your library application will respond to. Place the following code in it.

app_name = "libraryapp"

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^books$', book_list, name='books'),
    path('books/<int:book_id>/', book_details, name='book'),
    url(r'^book/form$', book_form, name='book_form'),
    url(r'^books/(?P<book_id>[0-9]+)/form$', book_edit_form, name='book_edit_form'),
    url(r'^librarians$', list_librarians, name='librarians'),
    path('librarians/<int:librarian_id>/', librarian_details, name='librarian'),
    url(r'^librarian/form$', librarian_form, name='librarian_form'),
    url(r'^library/form$', library_form, name='library_form'),
    url(r'^libraries$', list_libraries, name='libraries'),
    path('libraries/<int:library_id>/', library_details, name='library'),
    url(r'^libraries/(?P<library_id>[0-9]+)/form$', library_edit_form, name='library_edit_form'),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^logout/$', logout_user, name='logout'),







]

libraryproject/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from libraryapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('libraryapp.urls')),
]

libraryapp/models/book.py
from django.db import models
from .library import Library
from .librarian import Librarian


class Book(models.Model):

    title = models.CharField(max_length=100)
    isbn = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    year_published = models.IntegerField()
    location = models.ForeignKey(Library, on_delete=models.CASCADE)
    librarian = models.ForeignKey(Librarian, on_delete=models.CASCADE)

libraryapp/models/librarian.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .library import Library

class Librarian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.ForeignKey(
        Library, related_name="librarians",
        null=True, # Makes column nullable in DB
        blank=True, # Allows blank value on objects
        on_delete=models.CASCADE)

    # These receiver hooks allow you to continue to
# work with the `User` class in your Python code.


# Every time a `User` is created, a matching `Librarian`
# object will be created and attached as a one-to-one
# property
@receiver(post_save, sender=User)
def create_librarian(sender, instance, created, **kwargs):
    if created:
        Librarian.objects.create(user=instance)

# Every time a `User` is saved, its matching `Librarian`
# object will be saved.
@receiver(post_save, sender=User)
def save_librarian(sender, instance, **kwargs):
    instance.librarian.save()

libraryapp/models/library.py
from django.db import models

class Library(models.Model):

    title = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

libraryapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

libraryapp/views/connection.py
class Connection:
    db_path = "/Users/jeffh/workspace/python/libraryproject/db.sqlite3"

libraryapp/views/home.py
from django.shortcuts import render

def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

libraryapp/templates/books/detail.html
  {% extends 'shared/base.html' %}

{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    {% block content %}

    <section id="book-details">
        <h1>{{ book.title }}</h1>
        <h2>By {{ book.author }}</h2>

        <div>Published in {{ book.year_published }}</div>
        <div>ISBN: {{ book.isbn }}</div>
    </section>

    <section id="book-actions" style="display:flex;">
        <form action="{% url 'libraryapp:book' book.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button>Delete</button>
        </form>
      {% comment %} This produces the following HTML for the Edit button. {% endcomment %}
        <form action="{% url 'libraryapp:book_edit_form' book.id %}" method="GET">
            {% csrf_token %}
            <button>Edit</button>
        </form>
    </section>
      {% endblock %}

  </body>
</html>

libraryapp/templates/books/form.html
  {% extends 'shared/base.html' %}

{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>

  {% block content %}
    <h1>Inventory Book</h1>
  {% comment %} f the book.id parameter exists in the context, that means that the user is changing the current state of the book.
  Therefore, the POST request should be sent to /books/{id}.
  Otherwise, the user is creating a new book, and the POST request should be sent to /books. {% endcomment %}

    {% if book.id is not None %}
        <form action="{% url 'libraryapp:book' book.id %}" method="post">
    {% else %}
        <form action="{% url 'libraryapp:books' %}" method="post">
    {% endif %}
        {% csrf_token %}
        <fieldset>
            <label for="title">Title: </label>
            <input id="title" type="text" name="title" value="{{ book.title }}">
        </fieldset>
        <fieldset>
            <label for="author">Author: </label>
            <input id="author" type="text" name="author" value="{{ book.author }}">
        </fieldset>
        <fieldset>
            <label for="year_published">Year of publication: </label>
            <input id="year_published" type="number" name="year_published" value="{{ book.year_published }}">
        </fieldset>
        <fieldset>
            <label for="isbn">ISBN: </label>
            <input id="isbn" type="text" name="isbn" value="{{ book.isbn }}">
        </fieldset>
        <fieldset>
            <label for="location">Library: </label>
            <select id="location" type="text" name="location">
                {% for library in all_libraries %}
                <option {% if library.id == book.location_id %}selected{% endif %} value="{{ library.id }}">
                    {{ library.title }}</option>
                {% endfor %}
            </select>
        </fieldset>

        {% if book.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" />
        {% else %}
            <input type="submit" value="Create" />
        {% endif %}

    </form>
  {% endblock %}

  </body>
</html>

libraryapp/templates/books/list.html
  {% extends 'shared/base.html' %}

{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    {% block content %}

    <h1>Books</h1>
    <a href="{% url 'libraryapp:book_form' %}">Add Book to Inventory</a>

    <ol>
    {% comment %} When you want to write logical code in a Django template like for loops, or if statements,
    you need to wrap the code in {% %}. {% endcomment %}
    {% for book in all_books %}
        <li>
           <a href="{% url 'libraryapp:book' book.id %}"> {{ book.title }} </a>
            by {{book.author}} published in {{book.year_published}}
        </li>
    {% endfor %}
    </ol>
      {% endblock %}

  </body>
</html>

libraryapp/templates/home.html
  {% extends 'shared/base.html' %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Nashville Library Management System</title>
</head>

<body>
        {% block content %}

    <h1>Welcome to the Nashville Library Management System</h1>
              {% endblock %}

</body>

</html>

libraryapp/templates/librarians/detail.html
  {% extends 'shared/base.html' %}

{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
      {% block content %}

    <h1>{{ librarian.first_name }}</h1>
    <h2>By {{ librarian.last_name }}</h2>

    <form action="{% url 'libraryapp:librarian' librarian.id %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="actual_method" value="DELETE">
    <button>Delete</button>
    </form>
    {% endblock %}

  </body>
</html>

libraryapp/templates/librarians/form.html
  {% extends 'shared/base.html' %}

{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    {% block content %}

    <h1>Inventory Librarian</h1>


    <form action="{% url 'libraryapp:librarians' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="first_name">First Name: </label>
          <input id="first_name" type="text" name="first_name">
      </fieldset>
      <fieldset>
          <label for="last_name">Last Name: </label>
          <input id="last_name" type="text" name="last_name">
      </fieldset>
      <fieldset>
          <label for="location">Library: </label>
          <select id="location" type="text" name="location">
                {% for library in all_libraries %}
                    <option value="{{ library.id }}">{{ library.title }}</option>
                {% endfor %}
          </select>
      </fieldset>

      <input type="submit" value="Add It" />
    </form>
      {% endblock %}

  </body>
</html>

libraryapp/templates/librarians/list.html
  {% extends 'shared/base.html' %}

{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
      {% block content %}

    <h1>Librarians</h1>

    <ol>
    {% for librarian in all_librarians %}
         <li> <a href="{% url 'libraryapp:librarian' librarian.id%}">
        {{librarian.first_name}} {{librarian.last_name}}</a>
        </li>
    {% endfor %}
    </ol>
          {% endblock %}

  </body>
</html>

libraryapp/templates/libraries/detail.html
  {% extends 'shared/base.html' %}


{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
        {% block content %}

    <section id="library-details">
        <h1>{{ library.title }}</h1>
        <h2>By {{ library.address }}</h2>


    </section>

    <section id="library-actions" style="display:flex;">
        <form action="{% url 'libraryapp:library' library.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button>Delete</button>
        </form>

        <form action="{% url 'libraryapp:library_edit_form' library.id %}" method="GET">
            {% csrf_token %}
            <button>Edit</button>
        </form>
    </section>
              {% endblock %}

  </body>
</html>

libraryapp/templates/libraries/form.html
  {% extends 'shared/base.html' %}

{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
      {% block content %}

    <h1>Inventory Library</h1>


    {% if library.id is not None %}
        <form action="{% url 'libraryapp:library' library.id %}" method="post">
    {% else %}
        <form action="{% url 'libraryapp:libraries' %}" method="post">
    {% endif %}
        {% csrf_token %}
        <fieldset>
            <label for="title">Title: </label>
            <input id="title" type="text" name="title" value="{{ library.title }}">
        </fieldset>
        <fieldset>
            <label for="address">Address: </label>
            <input id="address" type="text" name="address" value="{{ library.address }}">
        </fieldset>

        {% if library.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" />
        {% else %}
            <input type="submit" value="Create" />
        {% endif %}

    </form>
          {% endblock %}

  </body>
</html>

libraryapp/templates/libraries/list.html
  {% extends 'shared/base.html' %}

{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
        {% block content %}

    <h1>Libraries</h1>
{% comment %} Then your templates/librarians/list.html template will iterate the all_librarians key on the context dictionary. {% endcomment %}
    <ol>
    {% for library in all_libraries %}
        <li><a href="{% url 'libraryapp:library' library.id %}">{{ library.title }}</a>
        located at {{ library.address }}</li>
    {% endfor %}
    </ol>
              {% endblock %}

  </body>
</html>

libraryapp/templates/shared/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Library</title>

    <style>
        .navList {
            list-style-type: none;
            display: flex;
            border: 1px solid lightgray;
            padding: 1em;
        }

        .navList__route {
            margin: 0 0.5em;
        }
    </style>
</head>

<body>

    <nav id="site-nav">
        <ol class="navList">
            <li class="navList__route"><a href="{% url 'libraryapp:libraries' %}">Libraries</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:books' %}">Books</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:librarians' %}">Librarians</a></li>
        </ol>
    </nav>

    {% block content %}
    {% endblock %}

</body>

</html>